#!/usr/bin/env bash
# /usr/bin/i3-maim
#
# simple screenshot-script using maim.

_conf=$HOME/.config/i3-maim-clpimg.conf

if ! [ -f $_conf ]; then
	echo "maim_dir=$(xdg-user-dir PICTURES)" > $_conf
fi

source $_conf

if ! [ -d $maim_dir ]; then
	mkdir -p $maim_dir
fi

if ! [[ -z "$2" ]]; then
    cmd="maim -d $2"
else
    cmd='maim'
fi

save_file="$maim_dir/$(date +%s).png"

case "$1" in
	--fullscreen|-f|$NULL)
	  $cmd $save_file &&
		notify-send "screenshot has been saved in $maim_dir" -a "i3-maim-clpimg" &&
		clpimg.py $save_file
		;;
	--window|-w)
		$cmd -i $(xdotool getactivewindow) $save_file &&
		notify-send "screenshot has been saved in $maim_dir" -a "i3-maim-clpimg" &&
		clpimg.py $save_file
		;;
	--select|-s)
		notify-send 'select an area for the screenshot' -a "i3-maim-clpimg" &
		$cmd -s $save_file &&
		notify-send "screenshot has been saved in $maim_dir" -a "i3-maim-clpimg" &&
		clpimg.py $save_file
		;;
	--help|-h)
		echo "
available options:
-f | --fullscreen    full screen
-w | --window  active window
-s | --select  selection
-h | --help    display this information
The -f or -w options can be used with a delay
by adding the number of seconds, like for example:
'i3-maim -w 5'
Default option is 'full screen'.
The file destination can be set in ${_conf}.
Default is $maim_dir
"
		;;
	*)
		echo "
== ! i3-maim-clpimg: missing or wrong argument ! ==
available options:
-f | --fullscreen    full screen
-w | --window  active window
-s | --select  selection
-h | --help    display this information
Default option is 'full screen'.
The -f or -w options can be used with a delay
by adding the number of seconds, like for example:
'i3-maim-clpimg -w 5'
Default option is 'full screen'.
The file destination can be set in ${_conf}.
Default is $maim_dir
"
	exit 2
esac

exit 0